"""add reminders_enabled and last_reminder_sent_date to teachers

Revision ID: 40f7ce5c5550
Revises: 8c225f329e0e
Create Date: 2026-07-14 20:05:34.769715

"""
from alembic import op
import sqlalchemy as sa


revision = '40f7ce5c5550'
down_revision = '8c225f329e0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('reminders_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('teachers', sa.Column('last_reminder_sent_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'last_reminder_sent_date')
    op.drop_column('teachers', 'reminders_enabled')
    # ### end Alembic commands ###
